"""intelligent_learning

Revision ID: 84848181e3df
Revises: 0003_username_auth
Create Date: 2026-07-09 10:09:56.721106

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '84848181e3df'
down_revision: Union[str, None] = '0003_username_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('section_slug', sa.String(length=255), nullable=False),
    sa.Column('concept_label', sa.String(length=512), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_concept_mastery_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_concept_mastery_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_mastery'))
    )
    op.create_index(op.f('ix_concept_mastery_topic_id'), 'concept_mastery', ['topic_id'], unique=False)
    op.create_index(op.f('ix_concept_mastery_user_id'), 'concept_mastery', ['user_id'], unique=False)
    op.create_table('resource_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_feedback_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resource_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_feedback'))
    )
    op.create_index(op.f('ix_resource_feedback_resource_id'), 'resource_feedback', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_feedback_user_id'), 'resource_feedback', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('answers_given', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_quiz_attempts_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_attempts_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    op.create_index(op.f('ix_quiz_attempts_module_id'), 'quiz_attempts', ['module_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.alter_column('artifact_sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifact_shells', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_artifact_shells_topic_id'), 'artifact_shells', type_='unique')
    op.drop_index(op.f('ix_artifact_shells_topic_id'), table_name='artifact_shells')
    op.create_index(op.f('ix_artifact_shells_topic_id'), 'artifact_shells', ['topic_id'], unique=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('curricula', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('curricula', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_content', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_generated_content_cache_key'), 'generated_content', type_='unique')
    op.drop_index(op.f('ix_generated_content_cache_key'), table_name='generated_content')
    op.create_index(op.f('ix_generated_content_cache_key'), 'generated_content', ['cache_key'], unique=True)
    op.add_column('learning_progress', sa.Column('best_quiz_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('learning_progress', sa.Column('quiz_attempt_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('learning_progress', sa.Column('streak_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('learning_progress', sa.Column('rag_interactions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('learning_progress', sa.Column('last_decay_applied', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('learning_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('learning_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('quizzes', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_quizzes_section_id'), 'quizzes', type_='unique')
    op.drop_index(op.f('ix_quizzes_section_id'), table_name='quizzes')
    op.create_index(op.f('ix_quizzes_section_id'), 'quizzes', ['section_id'], unique=True)
    op.alter_column('resource_refresh_logs', 'refreshed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('resources', sa.Column('feedback_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('resources', sa.Column('feedback_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_topics_slug'), 'topics', type_='unique')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.drop_constraint(op.f('uq_trusted_domains_domain'), 'trusted_domains', type_='unique')
    op.drop_index(op.f('ix_trusted_domains_domain'), table_name='trusted_domains')
    op.create_index(op.f('ix_trusted_domains_domain'), 'trusted_domains', ['domain'], unique=True)
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trusted_domains_domain'), table_name='trusted_domains')
    op.create_index(op.f('ix_trusted_domains_domain'), 'trusted_domains', ['domain'], unique=False)
    op.create_unique_constraint(op.f('uq_trusted_domains_domain'), 'trusted_domains', ['domain'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_topics_slug'), 'topics', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('resources', 'feedback_count')
    op.drop_column('resources', 'feedback_score')
    op.alter_column('resource_refresh_logs', 'refreshed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_quizzes_section_id'), table_name='quizzes')
    op.create_index(op.f('ix_quizzes_section_id'), 'quizzes', ['section_id'], unique=False)
    op.create_unique_constraint(op.f('uq_quizzes_section_id'), 'quizzes', ['section_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('quizzes', 'version')
    op.alter_column('provider_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('learning_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('learning_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('learning_progress', 'last_decay_applied')
    op.drop_column('learning_progress', 'rag_interactions')
    op.drop_column('learning_progress', 'streak_days')
    op.drop_column('learning_progress', 'quiz_attempt_count')
    op.drop_column('learning_progress', 'best_quiz_score')
    op.drop_index(op.f('ix_generated_content_cache_key'), table_name='generated_content')
    op.create_index(op.f('ix_generated_content_cache_key'), 'generated_content', ['cache_key'], unique=False)
    op.create_unique_constraint(op.f('uq_generated_content_cache_key'), 'generated_content', ['cache_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('generated_content', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('curricula', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('curricula', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_artifact_shells_topic_id'), table_name='artifact_shells')
    op.create_index(op.f('ix_artifact_shells_topic_id'), 'artifact_shells', ['topic_id'], unique=False)
    op.create_unique_constraint(op.f('uq_artifact_shells_topic_id'), 'artifact_shells', ['topic_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('artifact_shells', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifact_sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_module_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_resource_feedback_user_id'), table_name='resource_feedback')
    op.drop_index(op.f('ix_resource_feedback_resource_id'), table_name='resource_feedback')
    op.drop_table('resource_feedback')
    op.drop_index(op.f('ix_concept_mastery_user_id'), table_name='concept_mastery')
    op.drop_index(op.f('ix_concept_mastery_topic_id'), table_name='concept_mastery')
    op.drop_table('concept_mastery')
    # ### end Alembic commands ###
